locations/urls.py
from django.conf.urls import patterns, url
from locations import views

urlpatterns = patterns('',
    url(r'^add/', views.add, name='add'),
    url(r'^delete/', views.delete_location, name='delete_location'),
    url(r'^get/', views.get_locations, name='get_locations'),
    url(r'^card/', views.get_card),
    url(r'^card_list/', views.get_card_list),
    url(r'^profile/', views.get_profile),
    url(r'^change_field/', views.change_field),
    url(r'^json_list/', views.json_list),
    url(r'^json_matches_list/', views.json_matches_list),
)

sharedearth/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
import homepage.views
from django.views.generic.base import RedirectView
from sharedearth import settings
import static_pages.views
from django.views.generic.base import TemplateView
from messaging.views import jump_to_conversation
from profiles.views import jump_to_connection
from profiles.views import jump_to_marketing


admin.site.site_header = 'Shared Earth administration'
admin.site.site_title = 'Shared Earth administration'

urlpatterns = patterns('',
    # Actual pages
    url(r'^$', homepage.views.homepage, name='homepage'),
    url(r'^homepage$', homepage.views.homepage_force),
    url(r'^local-(?P<city>[^/]+)$', homepage.views.homepage),
    
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    url(r'^privacy$', static_pages.views.privacy_policy),
    url(r'^admin/', include(admin.site.urls)),

    # RESTful API 
    url(r'^images/', include('images.urls')),
    url(r'^locations/', include('locations.urls')),
    url(r'^tags/', include('tags.urls')),
    url(r'^messaging/', include('messaging.urls')),
    
    # All other URLs
    url(r'^conversation/(?P<token>[^/]+)/(?P<conversation_id>[0-9]+)', jump_to_conversation),
    url(r'^connection/(?P<token>[^/]+)/', jump_to_connection),
    url(r'^mkt/(?P<token>[^/]+)/', jump_to_marketing),
    url(r'^', include('profiles.urls')),
)

# Redirect all other pages to the homepage
if not settings.DEBUG:
    urlpatterns += patterns('',
        url('^.*/$', RedirectView.as_view(url='/', permanent=False)),
    )

tags/urls.py
from django.conf.urls import patterns, url
from tags import views

urlpatterns = patterns('',
    # Examples:
    url(r'^add/', views.add, name='add_tag'),
    url(r'^get/', views.get_list, name='get_tag_list'),
    url(r'^delete/', views.delete, name='delete_tag')
)

locations/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from taggit.managers import TaggableManager
from taggit.models import TaggedItemBase


class TaggedToolsIHave(TaggedItemBase):
    content_object = models.ForeignKey("Location")


class TaggedToolsINeed(TaggedItemBase):
    content_object = models.ForeignKey("Location")


class Location(models.Model):
    user = models.ForeignKey(User)

    # These fields are required in order to create the location
    formatted_address = models.CharField(max_length=256)
    
    street_number = models.CharField(max_length=64, blank=True, null=True)
    street_name = models.CharField(max_length=64, blank=True, null=True)
    city = models.CharField(max_length=64, blank=True, null=True)
    state = models.CharField(max_length=32, blank=True, null=True)
    county = models.CharField(max_length=32, blank=True, null=True)
    zip = models.CharField(max_length=5, blank=True, null=True)
    zip_plus_four = models.CharField(max_length=4, blank=True, null=True)
    country = models.CharField(max_length=32, blank=True, null=True) 
    
    latitude = models.FloatField()
    longitude = models.FloatField()
    type = models.CharField(max_length=32)              # For example, "have" or "need"

    uuid = models.CharField(max_length=36, unique=True)
    date_added = models.DateTimeField(default=timezone.now)
    
    avatar_url = models.CharField(max_length=256)
    map_icon_url = models.CharField(max_length=256)
    
    search_distance = models.FloatField(default=5.0)    # Default radius of 5 miles
    email_matches = models.BooleanField(default=True)
    
    # These can be filled in later, or not. No big deal.
    name = models.CharField(max_length=128, default=None, blank=True, null=True)
    about = models.TextField(default=None, blank=True, null=True)
    
    tools_i_have = TaggableManager(related_name='tools_i_have', through=TaggedToolsIHave)
    tools_i_need = TaggableManager(related_name='tools_i_need', through=TaggedToolsINeed)

    DISTANCE_CHOICES = (
        (0, "0.5 miles"),
        (1, "1 mile"),
        (2, "2 miles"),
        (5, "5 miles"),
        (10, "10 miles"),
        (20, "20 miles"),
        (50, "50 miles"),
    )
    distance = models.IntegerField(choices=DISTANCE_CHOICES, default=20)
    
    GARDEN_SIZE_CHOICES = (
        (0, "< 50 sq ft"),
        (1, "50 - 250 sq ft"),
        (2, "250 - 500 sq ft"),
        (3, "500 - 1000 sq ft"),
        (4, "1000 - 1500 sq ft"),
        (5, "1 acre"),
        (6, "5 acres"),
        (7, "10 acres"),
        (8, "20 acres"),
        (9, "50 acres"),
        (10, "100+ acres"),
    )
    garden_size = models.IntegerField(choices=GARDEN_SIZE_CHOICES, default=2)
    
    COMPENSATION_CHOICES = (
        (0, "Free to use"),
        (1, "Rent for money"),
        (2, "Share your harvest"),
        (3, "Other arrangement"),                         
    )
    compensation = models.IntegerField(choices=COMPENSATION_CHOICES, default=3)
    
    GARDEN_STATUS_CHOICES = (
        (0, "Ready to plant"),
        (1, "Needs some work"),
        (2, "Isn&rsquo;t a garden yet"),
    )
    garden_status = models.IntegerField(choices=GARDEN_STATUS_CHOICES, default=1) 
    
    haversine_distance = 0
    
    class Meta:
        index_together = [
            ["latitude", "longitude"],
            ["latitude", "longitude", "type"],
        ]

# EOF
    

profiles/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from taggit.models import TaggedItemBase
from django.utils import timezone
from locations.models import Location
import shortuuid
from datetime import timedelta


# User.display_name = property(lambda u: 
#     "%s %s." % (u.first_name, u.last_name[:1])
# )


class TaggedWhatIGrow(TaggedItemBase):
    content_object = models.ForeignKey("UserProfile")


class TaggedInterests(TaggedItemBase):
    content_object = models.ForeignKey("UserProfile")


# TODO: See http://stackoverflow.com/a/965883 for additional details on what
# needs to be configured with this. Doing it as an additional model rather
# than extending the base model intentionally. 
class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)   # Not "User" since we may be using a different model.
    referring_url = models.TextField(default=None, blank=True, null=True)  # The original URL the user came from
    about = models.TextField(default=None, blank=True, null=True)
    
    email_on_new_matches = models.BooleanField(default=True)
    email_on_messages = models.BooleanField(default=True)
    email_on_connect = models.BooleanField(default=True)
    email_on_resources = models.BooleanField(default=True)
    email_on_announcements = models.BooleanField(default=True)
    share_full_name_all = models.BooleanField(default=False)
    share_full_name_connected = models.BooleanField(default=True)
    share_address_connected = models.BooleanField(default=True)
    onboard = models.BooleanField(default=False)

    avatar_url = models.CharField(max_length=256, default=None, blank=True, null=True)

    what_i_grow = TaggableManager(related_name='what_i_grow', through=TaggedWhatIGrow)
    interests = TaggableManager(related_name='interests', through=TaggedInterests)

    EXPERIENCE_CHOICES = (
        (0, "New to gardening"),
        (1, "1 year"),
        (2, "2-5 years"),
        (5, "5-10 years"),
        (10, "10+ years"),
    )
    experience = models.IntegerField(choices=EXPERIENCE_CHOICES, default=2)
    
    RESPONSIBILITIES_CHOICES = (
        (0, "I'd like to work alone"),
        (1, "We could work together if you'd like"),
        (2, "I'm going to need some help")
    )
    responsibilities = models.IntegerField(choices=RESPONSIBILITIES_CHOICES, default=0)

    change_password_token = models.CharField(max_length=256, default=None, blank=True, null=True)
    change_password_token_expiration = models.DateTimeField(default=timezone.now)
    
    def __str__(self):  
        return "%s's profile" % self.user
    
    class Meta:
        permissions = (
            ("can_view_stats", "Can view stats"),
        )    
    

class Friendship(models.Model):
    user = models.ForeignKey(User)
    friend = models.ForeignKey(User, related_name="friendship_friend")
    time = models.DateTimeField(default=timezone.now)
    autologin_token = models.CharField(max_length=256, default=None, blank=True, null=True)
    autologin_token_expiration = models.DateTimeField(default=timezone.now)


class Notification(models.Model):
    user_notified = models.ForeignKey(User)
    location_notified_about = models.ForeignKey(Location)
    time = models.DateTimeField(default=timezone.now)


def generate_autologin_token():
    return str(shortuuid.ShortUUID().random(length=30))


def generate_autologin_expiration(days):
    return timezone.now() + timedelta(days=days)


class MarketingAutologin(models.Model):
    user = models.ForeignKey(User)
    autologin_token = models.CharField(max_length=256, default=None, blank=True, null=True, db_index=True)
    autologin_token_expiration = models.DateTimeField(default=timezone.now)
    destination_url = models.CharField(max_length=512, default=None, blank=True, null=True)
    

# EOF

locations/templates/locations/location_card.html
<div class="single-map-note">
  <div class="map-name">
    <img src="{{location.avatar_url}}" class="avi">
    <h2>{{user_display_name}}{% if location.type == 'have' and location.name != None and location.name|length %}<br>{{ location.name }}{% endif %}</h2>
    {% if back %}<button class="back" onclick="infoWindowBack();">&laquo;</button>{% endif %}
  </div>
  <div class="map-bio">
    <ul>

      <li>{% if location.type = "have" %}Has a garden to share.{%else%}Looking for a garden.{%endif%}</li>

      {% if what_i_like_to_grow %}
      <li>Likes to grow:
        {% for what in what_i_like_to_grow %}<b>{{what}}</b>{%include "comma.html"%} {% endfor %}  
      </li>
      {% endif %}

      {% if interests %}
      <li>Interests:
        {% for what in interests %}<b>{{what}}</b>{%include "comma.html"%} {% endfor %}  
      </li>
      {% endif %}

      {% if tools_i_have %}
      <li>Tools shared:
        {% for tool in tools_i_have %}<b>{{tool}}</b>{%include "comma.html"%} {% endfor %}  
      </li>
      {% endif %}

      {% if tools_i_need %}
      <li>Tools needed:
        {% for tool in tools_i_need %}<b>{{tool}}</b>{%include "comma.html"%} {% endfor %}  
      </li>
      {% endif %}

      <li>{{ distance }} from you.</li>
    </ul>
  </div>
  <div class="map-note-nav">
    <button class="profile" onclick="viewLocationProfile({{location.id}});">View Profile</button> <button onclick="beginMessage({{location.user.id}},{{location.id}});" class="message">Message</button>
  </div>
</div>

locations/templates/locations/location_card_list.html
<div class="multi-map-note">
  {% for location in locations %}
  <div class="map-name" onclick="viewLocationProfile({{location.id}}); return false;">
    <img src="{{location.avatar_url}}" class="avi">
    <h2 style="text-align: left">{% if location.type == 'have' and location.name != None and location.name|length %}{{ location.name }}{%else%}{{location.user_display_name}}{%endif%}</h2>
    <button class="next">&raquo;</button>
  </div>
  {% endfor %}
</div>

locations/templates/locations/location_profile.html
{% collapsewhitespace %}
<div class="place_profile">

  <div class="header">
    <img src="{{location.user.userprofile.avatar_url}}" class="avi{% if self %} self{% endif %}">
    <div class="name">
      <h2>{{user_display_name}}</h2>
      <p>{% if location.type == 'have'%}{% if location.name != None and location.name|length %}{{ location.name }}{%else%}Garden{%endif%}{%else%}Looking for a garden{%endif%}</p>
      <p>{{city_state}}</p>
    </div>
    <div>{% if not self %}<button onclick="beginMessage({{location.user.id}},{{location.id}});" class="message">Message</button>{% else %}<button onclick="mainScope.profileEditButtonClicked('{{location.uuid}}');" class="edit">Edit</button>{% endif %}</div>
  </div>

  <div class="buttons1">
  </div>
  
  <div class="profile-content">
    <h3>Location</h3>
    <div id="tiny-map" data-lat="{{location.latitude}}" data-lng="{{location.longitude}}" data-icon="{{location.map_icon_url}}"></div>

    {% if images %}
    <h3>Photos</h3>
    <div id="tiny-images-list">{% include 'images/tiny_image_list.html' %}</div>
    {% endif %}
  
    {% if location.about %}
    <h3>About this garden</h3>
    <p>{{location.about}}</p>
    {% endif %}
    
    {% if profile.about %}
    <h3>About {{user_display_name}}</h3>
    <p>{{profile.about}}</p>
    {% endif %}
        
    <h3>Experience</h3>
    <p>{{profile.get_experience_display}}</p>
    
    {% if location.type == 'need'%}
    <h3>Search Radius</h3>
    <p>{{location.get_distance_display}}</p>
    {% endif %}
    
    {% if what_i_like_to_grow %}
    <h3>Likes to grow</h3>
    <p>{% for what in what_i_like_to_grow %}<b>{{what}}</b>{%include "comma.html"%} {% endfor %}</p> 
    {% endif %}

    {#
    {% if interests %}
    <h3>Interests</h3>
    <p>{% for what in interests %}<b>{{what}}</b>{%include "comma.html"%} {% endfor %}</p>
    {% endif %}
    #}

    {% if tools_i_have %}
    <h3>Tools shared</h3>
    <p>{% for tool in tools_i_have %}<b>{{tool}}</b>{%include "comma.html"%} {% endfor %}</p>
    {% endif %}

    {% if tools_i_need %}
    <h3>Tools needed</h3>
    <p>{% for tool in tools_i_need %}<b>{{tool}}</b>{%include "comma.html"%} {% endfor %}</p>  
    {% endif %}
    
    {% if other_gardens.count > 0 %}
    <h3>{% if location.type == 'have'%}Other gardens{% else %}Gardens{% endif %}</h3>
    <ul class="gardens">
    {% for l in other_gardens %}
    <li onclick="viewLocationProfile({{l.id}});">
      <img src="{{l.avatar_url}}" class="avi">
      <span>
        {% if l.name != None and l.name|length %}{{ l.name }}{%else%}Garden{%endif%}<br>
        ({% if l.city %}{{ l.city }}, {% endif %}{{ l.state }})
      </span>
      <button class="next">&raquo;</button>
    </li>
    {% endfor %}
    </ul>
    {% endif %}

    {% if other_gardeners.count > 0 %}
    <h3>{% if location.type == 'need'%}Looking for gardens{% else %}Looking for gardens{% endif %}</h3>
    <ul class="gardens">
    {% for l in other_gardeners %}
    <li onclick="viewLocationProfile({{l.id}});">
      <img src="{{l.avatar_url}}" class="avi">
      <span>
        {% if l.name != None and l.name|length %}{{ l.name }}{%else%}Looking for a garden{%endif%}<br>
        ({% if l.city %}{{ l.city }}, {% endif %}{{ l.state }})
      </span>
      <button class="next">&raquo;</button>
    </li>
    {% endfor %}
    </ul>
    {% endif %}
      
  </div>
</div>
{% endcollapsewhitespace %}